In [1]:
!pip install -U scipy==1.10.0 numpy==1.23.5

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 38.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.4
    Uninstalling scipy-1.11.4:
      Successfully uninstalled scipy-1.11.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chex 0.1.85 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.


In [2]:
!pip install -U git+https://github.com/stephenhky/PyShortTextCategorization

  Cloning https://github.com/stephenhky/PyShortTextCategorization to /tmp/pip-req-build-das3mn_0
  Running command git clone --filter=blob:none --quiet https://github.com/stephenhky/PyShortTextCategorization /tmp/pip-req-build-das3mn_0
  Resolved https://github.com/stephenhky/PyShortTextCategorization to commit e183bac2a362051087e3cb9160ccd8f2ee67f315
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.4/177.4 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 13.9 MB/s eta 0:00:00
  Created wheel for shorttext: filename=shorttext-1.6.1-cp310-cp310-linux_x86_64.whl size=724849 sha256=2e718c1de6b815bee58c3bd5523fbae57c748f5c25c4cedf40c8f7f73f7e0e97
  Stored in directory: /tmp/pip-ephem-wheel-cache-qsh7a43a/wheels/84/07/3e/bb56d79459e5c3c9111c649d174481179ef9258e9559bdd72c
Successfully

In [3]:
!python -m spacy download en

⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 20.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [3]:
%cd /content/drive/My Drive/DSBA

/content/drive/My Drive/DSBA


In [4]:
from nltk.corpus import PlaintextCorpusReader
corpus_root = 'MovieReviews' # Folder Name
filelists = PlaintextCorpusReader(corpus_root, '.*',encoding='latin-1')  # wildcard is read all files in the folder
filelists.fileids()  # Get the filenames

['MovieReviews/16748.txt',
 'MovieReviews/17108.txt',
 'MovieReviews/17109.txt',
 'MovieReviews/17110.txt',
 'MovieReviews/17111.txt',
 'MovieReviews/17116.txt',
 'MovieReviews/17117.txt',
 'MovieReviews/17118.txt',
 'MovieReviews/17119.txt',
 'MovieReviews/17139.txt',
 'MovieReviews/17144.txt',
 'MovieReviews/17145.txt',
 'MovieReviews/17146.txt',
 'MovieReviews/17147.txt',
 'MovieReviews/17150.txt',
 'MovieReviews/17185.txt',
 'MovieReviews/17192.txt',
 'MovieReviews/17219.txt',
 'MovieReviews/17239.txt',
 'MovieReviews/17243.txt',
 'MovieReviews/17254.txt',
 'MovieReviews/17255.txt',
 'MovieReviews/17280.txt',
 'MovieReviews/17300.txt',
 'MovieReviews/17303.txt',
 'MovieReviews/17341.txt',
 'MovieReviews/17384.txt',
 'MovieReviews/17391.txt',
 'MovieReviews/17398.txt',
 'MovieReviews/17399.txt',
 'MovieReviews/17430.txt',
 'MovieReviews/17431.txt',
 'MovieReviews/17447.txt',
 'MovieReviews/17457.txt',
 'MovieReviews/17460.txt',
 'MovieReviews/17501.txt',
 'MovieReviews/17518.txt',
 

In [5]:
#create a list of movie reviews
reviews = []
for fileid in filelists.fileids():
    reviews.append(filelists.raw(fileid))

In [6]:
reviews[25]

'THE BED YOU SLEEP IN (director: Jon Jost; cast: Ray Weiss (Tom Blair), Doug (Marshall Gaddis), Beth (Kate Sannella), Scott (Brad Shelton), Mrs. Weiss (Ellen McLaughlin), 1993)\nTruly independent filmmaker, Jost, has completed his so-called trilogy about rural America with this film and has since moved on to self- imposed exile by going to Europe. This extra-ordinary film offers a long hard look at its subject matter, as the camera is held steadfast, not moving for insatiably long periods of time, picking up all the appropriate nuances it needs to with deliberate dispassion, as it looks at an Oregon lumber mill, whose owner (Tom Blair) is faced with unsettling economic news about the business he has built-up and worked at for his 50- odd years of life. It focuses on this man and tries to find out who he is, using him as a metaphoric symbol for America, perhaps, emulating Emerson\'s views, as his writings are flashed on screen, exhibiting some sayings from his essays on nature and Ameri

In [7]:
# import the shorttext library for text preprocessing
#standard_text_preprocessor_1 under shorttext.utils provides a standar way of text preprocessing, including the following steps:

   #1. removing special characters,
   #2. removing numerals,
   #3. converting all alphabets to lower cases,
   #4. removing stop words, and
   #5. stemming the words (using Porter stemmer).

from shorttext.utils import standard_text_preprocessor_1, DocumentTermMatrix
preprocessor = standard_text_preprocessor_1()
corpus = [preprocessor(article).split(' ') for article in reviews]

In [8]:
corpus[25]

['bed',
 'sleep',
 'director',
 'jon',
 'jost',
 'cast',
 'rai',
 'weiss',
 'tom',
 'blair',
 'doug',
 'marshal',
 'gaddi',
 'beth',
 'kate',
 'sannella',
 'scott',
 'brad',
 'shelton',
 'mr',
 'weiss',
 'mclaughlin',
 '\ntruli',
 'independ',
 'filmmak',
 'jost',
 'complet',
 'socal',
 'trilogi',
 'rural',
 'america',
 'film',
 'sinc',
 'move',
 'self',
 'impos',
 'exil',
 'go',
 'europ',
 'extraordinari',
 'film',
 'offer',
 'long',
 'hard',
 'look',
 'subject',
 'matter',
 'camera',
 'held',
 'steadfast',
 'move',
 'insati',
 'long',
 'period',
 'time',
 'pick',
 'appropri',
 'nuanc',
 'need',
 'deliber',
 'dispass',
 'look',
 'oregon',
 'lumber',
 'mill',
 'whose',
 'owner',
 'tom',
 'blair',
 'face',
 'unsettl',
 'econom',
 'new',
 'busi',
 'builtup',
 'work',
 '',
 'odd',
 'year',
 'life',
 'focus',
 'tri',
 'find',
 'us',
 'metaphor',
 'symbol',
 'america',
 'perhap',
 'emul',
 'emerson',
 'view',
 'write',
 'flash',
 'screen',
 'exhibit',
 'sai',
 'essai',
 'natur',
 'america\nb

In [9]:
#convert the corpus of news to a document term matrix (dtm), where each row represents a document, each column represents the number of occurence for a word
dtm = DocumentTermMatrix(corpus, docids = filelists.fileids())

In [10]:
#check number of occurence of the word "director" in each document
dtm.get_token_occurences('director')

{'MovieReviews/16748.txt': 3.0,
 'MovieReviews/17108.txt': 3.0,
 'MovieReviews/17109.txt': 1.0,
 'MovieReviews/17110.txt': 2.0,
 'MovieReviews/17111.txt': 1.0,
 'MovieReviews/17116.txt': 1.0,
 'MovieReviews/17117.txt': 5.0,
 'MovieReviews/17118.txt': 1.0,
 'MovieReviews/17119.txt': 5.0,
 'MovieReviews/17139.txt': 1.0,
 'MovieReviews/17144.txt': 1.0,
 'MovieReviews/17145.txt': 2.0,
 'MovieReviews/17146.txt': 2.0,
 'MovieReviews/17147.txt': 1.0,
 'MovieReviews/17150.txt': 1.0,
 'MovieReviews/17185.txt': 3.0,
 'MovieReviews/17192.txt': 4.0,
 'MovieReviews/17219.txt': 1.0,
 'MovieReviews/17239.txt': 2.0,
 'MovieReviews/17243.txt': 1.0,
 'MovieReviews/17254.txt': 1.0,
 'MovieReviews/17255.txt': 1.0,
 'MovieReviews/17280.txt': 2.0,
 'MovieReviews/17300.txt': 2.0,
 'MovieReviews/17303.txt': 2.0,
 'MovieReviews/17341.txt': 1.0,
 'MovieReviews/17384.txt': 2.0,
 'MovieReviews/17398.txt': 1.0,
 'MovieReviews/17399.txt': 3.0,
 'MovieReviews/17430.txt': 2.0,
 'MovieReviews/17431.txt': 2.0,
 'MovieR

In [11]:
type(dtm.get_token_occurences('director'))

dict

In [12]:
# define a function to calculate entropy given a distribution
import numpy as np
import math

def entropy(p):
    if sum(p) == 0:
        return 0

    p = p/sum(p)

    p = p[ p > 0 ]

    H = -sum(p*np.log2(p))

    return H

In [13]:
director_word_count = list(dtm.get_token_occurences('director').values())
director_doc_count = list(dtm.get_token_occurences('director').keys())

In [14]:
#indexing files to separate authors of reviews
berardinelli = filelists.fileids()[:80]
schwartz = filelists.fileids()[80:180]

In [15]:
#checking the correct length
print(len(berardinelli))
print(len(schwartz))

80
100


In [16]:
#ensuring there are no duplicates
print(berardinelli)
print(schwartz)

['MovieReviews/16748.txt', 'MovieReviews/17108.txt', 'MovieReviews/17109.txt', 'MovieReviews/17110.txt', 'MovieReviews/17111.txt', 'MovieReviews/17116.txt', 'MovieReviews/17117.txt', 'MovieReviews/17118.txt', 'MovieReviews/17119.txt', 'MovieReviews/17139.txt', 'MovieReviews/17144.txt', 'MovieReviews/17145.txt', 'MovieReviews/17146.txt', 'MovieReviews/17147.txt', 'MovieReviews/17150.txt', 'MovieReviews/17185.txt', 'MovieReviews/17192.txt', 'MovieReviews/17219.txt', 'MovieReviews/17239.txt', 'MovieReviews/17243.txt', 'MovieReviews/17254.txt', 'MovieReviews/17255.txt', 'MovieReviews/17280.txt', 'MovieReviews/17300.txt', 'MovieReviews/17303.txt', 'MovieReviews/17341.txt', 'MovieReviews/17384.txt', 'MovieReviews/17391.txt', 'MovieReviews/17398.txt', 'MovieReviews/17399.txt', 'MovieReviews/17430.txt', 'MovieReviews/17431.txt', 'MovieReviews/17447.txt', 'MovieReviews/17457.txt', 'MovieReviews/17460.txt', 'MovieReviews/17501.txt', 'MovieReviews/17518.txt', 'MovieReviews/17532.txt', 'MovieRevie

In [17]:
#The number of berardinelli docs containing director
b_count: int = sum([1 for doc in director_doc_count if doc in berardinelli])
print('The number of berardinelli docs containing director:', b_count)

The number of berardinelli docs containing director: 77


In [18]:
#The number of berardinelli docs NOT containing director
b_null: int = 80 - 77
print('The number of berardinelli docs NOT containing director:', b_null)

The number of berardinelli docs NOT containing director: 3


In [19]:
#The number of schwartz docs containing director
s_count: int = sum([1 for doc in director_doc_count if doc in schwartz])
print('The number of schwartz docs containing director:', s_count)

The number of schwartz docs containing director: 85


In [20]:
#The number of schwartz docs NOT containing director
s_null: int = 100 - 85
print('The number of schwartz docs NOT containing director:', s_null)

The number of schwartz docs NOT containing director: 15


In [21]:
#this is an important step
#make an array, rows represent "Berardinelli" and "Schwartz" respectively.
#Columns represent the number of documents that contains the word "director" and the number of documents that do NOT contain the word "director"

array = np.reshape((b_count, 80-b_count, s_count, 100-s_count),(2,2))
array

array([[77,  3],
       [85, 15]])

In [22]:
#calculate the column sum of the array
np.sum(array, axis = 0)

array([162,  18])

**Problem 1**
Please calculate the entropy of the word “director” appearance in the 180 documents.

In [23]:
#calculate the entropy of the word "director"
entropy(np.array([162,18]))

0.4689955935892812

In [24]:
#calculate the row sum of the array
np.sum(array, axis = 1)

array([ 80, 100])

In [25]:
#calculate the entropy of the author (berardinelli, schwartz)
entropy_class = entropy(np.sum(array, axis = 1))
entropy_class

0.9910760598382222

In [26]:
#calculate the column probabilities
column_probs = np.sum(array, axis = 0)/180
column_probs

array([0.9, 0.1])

In [27]:
#calculate the column entropies
column_entropy = np.apply_along_axis(entropy, 0, array)
column_entropy

array([0.99824017, 0.65002242])

In [28]:
#calculate conditional entropy
conditional_entropy = sum(column_probs*column_entropy)
conditional_entropy

0.9634183936209307

**Problem 2**
Calculate the mutual information between the “director” and the document author.


In [29]:
#calculate the mutual information between the word "director" and the author
mutual_information = entropy_class - conditional_entropy
mutual_information

0.027657666217291488

**Problem 3**
Find the top ten words with the highest mutual information with the document author and their respective mutual information. Explain (in Python comments) that what it means for a word by having a high mutual information with the document author.


In [30]:
vocabulary = {}
for document in corpus:
    for word in document:
        if word not in vocabulary:
            vocabulary[word] = 1
        else:
            vocabulary[word] += 1

In [31]:
def word_association(word):
  director_word_count = list(dtm.get_token_occurences(word).values())
  director_doc_count = list(dtm.get_token_occurences(word).keys())

  print('Entropy of `{}` in the documents:'.format(word), entropy(director_word_count))

  b_count: int = sum([1 for doc in director_doc_count if doc in berardinelli])
  print('The number of berardinelli docs containing {}:'.format(word), b_count)

  s_count: int = sum([1 for doc in director_doc_count if doc in schwartz])
  print('The number of schwartz docs containing {}:'.format(word), s_count)

  array = np.reshape((b_count, 80-b_count, s_count, 100-s_count),(2,2))
  print('Matrix:', array)

  entropy_class = entropy(np.sum(array, axis = 1))
  print('Entropy Class:', entropy_class)

  column_probs = np.sum(array, axis = 0)/180
  print('Column Probabilities:', column_probs)

  column_entropy = np.apply_along_axis(entropy, 0, array)
  print('Column Entropy:', column_entropy)

  conditional_entropy = sum(column_probs*column_entropy)
  print('Conditional Entropy:', conditional_entropy)

  mutual_information = entropy_class - conditional_entropy
  print('Mutual Information:', mutual_information)


In [32]:
there = word_association('there')

Entropy of `there` in the documents: 5.322579324069085
The number of berardinelli docs containing there: 0
The number of schwartz docs containing there: 50
Matrix: [[ 0 80]
 [50 50]]
Entropy Class: 0.9910760598382222
Column Probabilities: [0.27777778 0.72222222]
Column Entropy: [-0.         0.9612366]
Conditional Entropy: 0.6942264367442992
Mutual Information: 0.29684962309392304


In [33]:
right = word_association('right')

Entropy of `right` in the documents: 6.679392948034621
The number of berardinelli docs containing right: 79
The number of schwartz docs containing right: 40
Matrix: [[79  1]
 [40 60]]
Entropy Class: 0.9910760598382222
Column Probabilities: [0.66111111 0.33888889]
Column Entropy: [0.92107152 0.12068101]
Conditional Entropy: 0.6498280710388034
Mutual Information: 0.34124798879941887


In [34]:
def word_association_final(word):
  director_word_count = list(dtm.get_token_occurences(word).values())
  director_doc_count = list(dtm.get_token_occurences(word).keys())

  entropy_value = entropy(director_word_count)

  b_count: int = sum([1 for doc in director_doc_count if doc in berardinelli])

  s_count: int = sum([1 for doc in director_doc_count if doc in schwartz])

  array = np.reshape((b_count, 80-b_count, s_count, 100-s_count),(2,2))

  entropy_class = entropy(np.sum(array, axis = 1))

  column_probs = np.sum(array, axis = 0)/180

  column_entropy = np.apply_along_axis(entropy, 0, array)

  conditional_entropy = sum(column_probs*column_entropy)

  mutual_information = entropy_class - conditional_entropy
  return mutual_information

mi_scores = {}
for word in vocabulary.keys():
    mi_score = word_association_final(word)
    mi_scores[word] = mi_score

sorted_scores = sorted(mi_scores.items(), key = lambda x: x[1], reverse = True)

top_ten = [word for word, _ in sorted_scores[:10]]

print('Words with Highest MI:')
for word, mi_score in sorted_scores [:10]:
  print(f'{word}:{mi_score}')

Words with Highest MI:
reserv:0.5360547127375266
denni:0.5177766824991015
schwartz
:0.49202296056300543
right:0.34124798879941887
there:0.29684962309392304
howev:0.27421790253727896
releas:0.2702108404097968
cast:0.2564686677667559
screenplai:0.2564686677667559
produc:0.23020448708340835


**Explain what it means for a word by having a high mutual information with the document author.**

Mutual Information provides a way to discover syntagmatic relationships. If an author has high mutual information between some words, it will be easier to identify what syntax or words they use in their work as well as better identify their writing style or tendencies. We can know what topics they prefer, and what they like to evaluate.